# Usa una imagen oficial de Node.js como base
FROM node:22-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias primero para aprovechar el cache de Docker
COPY package*.json ./

# Copia el resto del código fuente
COPY . .

# Instala las dependencias de npm
RUN npm install --force